### ISSUE TITLE
Spontaneous termination of DF

### ISSUE THREAD

**Issue by Opusm** [Noeda/dfterm3#15]
Once I launch DF through the web interface, the game only seems to function for about 10-20 seconds before the process terminates itself (regardless of if I leave it on title screen, load a game, create a world etc.) and then becomes unable to relaunch until I completely restart DFTerm.

I took a screenshot of the terminal to help you troubleshoot.

http://img6.imageshack.us/img6/8357/c7wz.jpg

**Comment by lethosor** [comment]
(Side note:) I'm experiencing something similar with testing on OS X - once a game has been launched and quit, it no longer launches from the playing interface until the server is restarted (although I haven't noticed it terminating itself yet). I have yet to test this on Linux.
Anyway, my only advice here is to make sure you have the correct version of DFhack. I don't have much experience with running this on Windows, so @Noeda would probably be more helpful.

**Comment by Opusm** [comment]
This is with a fresh unmodified download of Dwarf Fortress (0.34.11) and DFHack version 34.11-r3 under windows 7. (Hopefully that should narrow things down a bit).

**Comment by Noeda** [comment]
The process is closed because Dfterm3 automatically kills Dwarf Fortress it launches if it cannot get connection. This is to prevent Dwarf Fortresses accumulating that Dfterm3 knows nothing about.

It seems that, for some reason, Dfterm3 is not able to connect to the Dfhack Dfterm3 plugin in Dwarf Fortress. Does the Dfhack console say "Dfterm3 service started on port 48000"? If it does, then my best guess is that for some reason, Dfterm3 is blocked from connecting to Dwarf Fortress. Do you have any special firewalls or something else that you could think would block the connection?

That HTTP error message in console is bizarre because I don't think Dfterm3 makes any HTTP requests.

... I had no idea Dfterm3 even compiles on OS X.

**Comment by Opusm** [comment]
This issue has now been resolved. I had incorrectly installed the custom DFHack to the DFTerm folder rather than the actual game folder therefore DFTerm never launched. So for future reference, the issue is with an incorrectly installed DFHack r-3.
