### ISSUE TITLE
All port options must be specified on command-line

### ISSUE THREAD

**Issue by lethosor** [Noeda/dfterm3#2]
I'm not sure if this is intentional, but when trying to specify a different port for the playing server with `--websocket-http=` (since I'm running a server on 8080 already), only the playing server starts (the admin server and socket don't). It would be nice to be able to use defaults for the other ports without specifying them explicitly. As an alternative, I suppose another option could be added to run only the servers specified, in case it turns out to be necessary.

**Comment by Noeda** [comment]
This was me trying to make things easier for my first users by having some default command line options if none are specified.

I see two obvious ways to change this:
- Don't have any default options. Users will have to specify them all.
- Always use the default ports, in addition to any user-specified ports, unless a specific command line option is given to turn the default ports off

I'm leaning for the latter option because so far we have no launcher or installer that would give the ports for our less technically talented users.
